name: build

on: [workflow_dispatch]

jobs:
  windows-msys:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        cc: [gcc]
        include:
          # - arch: x86
          #   msystem: MINGW32
          #   prefix: mingw-w64-i686

          - arch: x86_64
            msystem: MINGW64
            prefix: mingw-w64-x86_64

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: base-devel ${{ matrix.prefix }}-toolchain ${{ matrix.prefix }}-cmake ${{ matrix.prefix }}-ninja ${{ matrix.prefix }}-qt5-base ${{ matrix.prefix }}-qt5-svg ${{ matrix.prefix }}-libxml2 git unzip p7zip
        msystem: ${{ matrix.msystem }}
        path-type: minimal
        release: false
        update: false

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure
      run: |
        cmake -S. --preset DefaultNinja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build --preset DefaultNinja
        7z a Windows-${{ matrix.arch }}.zip ./install/*

    - uses: actions/upload-artifact@v4
      with:
        name: Windows-${{ matrix.arch }}
        path: Windows-${{ matrix.arch }}.zip
        if-no-files-found: error

  linux:
    name: ${{ matrix.config }} Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]

    steps:
    - name: Install tools
      run: |
          sudo apt-get -qq update
          sudo apt-get -y install mesa-common-dev qtbase5-dev libqt5svg5-dev libjpeg-dev libpng-dev
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure
      run: |
        cmake -S. --preset DefaultNinja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build --preset DefaultNinja
        7z a Linux-${{ matrix.arch }}.7z ./install/*

    - uses: actions/upload-artifact@v4
      with:
        name: Linux-${{ matrix.arch }}
        path: Linux-${{ matrix.arch }}.7z
        if-no-files-found: error
